# Equivalencias entre clases y nombres

def transformToClassName(name):
    if name in clases: 
        return clases[name]
    else:
        # if name not in clases.values():
        #     print(name)
        return name

clases = {
    'Species 81': 'Dentex dentex'
    ,'Species 82': 'Seriola dumerilií'            
    ,'Species 83': 'Sarda sarda'               
    ,'Species 84': 'Mullus surmulentus'          
    ,'Species 85': 'Merlucius merlucius'
    ,'Species 86': 'Sparus aurata'
    ,'Species 87': 'Pagellus erythrinus'
    ,'Species 1': 'Sardinella aurita'
    ,'Species 2': 'Dactylopterus volitans'
    ,'Species 3': 'Trachurus mediterraneus'
    ,'Species 4': 'Diplodus sargus'
    ,'Species 5': 'Trachinus draco'
    ,'Species 6': 'Symphodus tinca M'
    ,'Species 7': 'Diplodus vulgaris'
    ,'Species 8': 'Mugil cephalus'
    ,'Species 9': 'Raja asterias'
    ,'Species 10': 'Spondyliosoma cantharus'
    ,'Species 11': 'Sciaena umbra'
    ,'Species 12': 'Zeus faber'
    ,'Species 13': 'Scorpaena porcus'
    ,'Species 14': 'Uranoscopus scaber'
    ,'Species 15': 'Chelidonichthys lastoviza'
    ,'Species 16': 'Symphodus mediterraneus'
    ,'Species 17': 'Spicara smaris'
    ,'Species 18': 'Spicara maena'
    ,'Species 19': 'Microchirus ocellatus'
    ,'Species 20': 'Sphyraena sphyraena'
    ,'Species 21': 'Pagrus pagrus'
    ,'Species 22': 'Pagellus acarne'
    ,'Species 23': 'Mullus barbatus'
    ,'Species 24': 'Sarpa salpa'
    ,'Species 25': 'Pomadasys incisus'
    ,'Species 26': 'Scomber japonicus'
    ,'Species 27': 'Labrus merula'
    ,'Species 28': 'Labrus viridis'
    ,'Species 29': 'Muraena helena'
    ,'Species 30': 'Lophius sp'
    ,'Species 31': 'Raja radula'
    ,'Species 32': 'Serranus scriba'
    ,'Species 33': 'Scorpaena notata'
    #,'Species 34': 'Raja radula'#
    ,'Species 35': 'Conger conger'
    ,'Species 36': 'Diplodus anularis'
    ,'Species 37': 'Scorpaena scrofa'
    ,'Species 38': 'Symphodus tinca H'
    ,'Species 39': 'Mustelus mustelus'
    ,'Species 40': 'Dicentrarchus labrax'
    ,'Species 41': 'Serranus cabrilla'
    ,'Species 42': 'Boops boops'
    ,'Species 43': 'Balistes capriscus'
    ,'Species 44': 'Pomatomus saltatrix'
    ,'Species 45': 'Torpedo marmorata'
    ,'Species 46': 'Umbrina cirrosa'
    ,'Species 47': 'Phycis phycis'
    ,'Species 48': 'Lithognathus mormyrus'
    ,'Species 60': 'Sepia officinalis'
    ,'Species 49': 'Species 49'
    ,'Species 50': 'Species 50'
    ,'Species 51': 'Species 51'
    ,'Species 52': 'Species 52'
    ,'Species 53': 'Species 53'
    ,'Species 54': 'Species 54'
    ,'Species 55': 'Species 55'
    ,'Species 56': 'Species 56'
    ,'Species 57': 'Species 57'
    ,'Species 58': 'Species 58'
    ,'Species 59': 'Species 59'
    ,'Species 61': 'Species 61'
    ,'Species 62': 'Species 62'
    ,'Species 63': 'Species 63'
    ,'Species 64': 'Species 64'
    ,'Species 65': 'Species 65'
    ,'Species 66': 'Species 66'
    ,'Species 67': 'Species 67'
    ,'Species 68': 'Species 68'
    ,'Species 69': 'Species 69'
    ,'Species 70': 'Species 70'
    ## Cambios que se han realizado, esta es la corrección
    ,'Symphodus tinca': 'Symphodus tinca M'
    ,'Scorpaena': 'Scorpaena scrofa'
    ,'Trachurus spp': 'Trachurus mediterraneus'
    ,'RAYA': 'Raja asterias'
    

}